name: Update Previous Standings

on:
  schedule:
    - cron: '2 0 * * 0' # Sunday 00:02 UTC, after save-weekly-standings
  workflow_dispatch:

jobs:
  update-standings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Update previous standings
        run: npm run update-standings

      - name: Commit updated previousStandings.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add previousStandings.json
          git commit -m "Update previous standings for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
