name: Update Previous Standings

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-standings:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the update-standings script
      - name: Update previous standings
        run: npm run update-standings

      # Step 5: Commit and push changes
      - name: Commit updated previousStandings.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add previousStandings.json
          git commit -m "Update previous standings for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
